### ISSUE TITLE
review- 2018.12.08-刘文杰

### ISSUE THREAD

**Issue by liuwenjie1995** [DIYer22/weekly-review#390]
# 本周工作:
训练了facelet bank 的encoder 和decoder 层, 下周完成其余工作出结果.
重写DFI内容,效果有一定提升

戴眼镜, 张嘴,男性,胡须,微笑,年轻
![avatar](https://s1.ax1x.com/2018/12/08/F36Jlq.png)
![avatar](https://i.loli.net/2018/12/08/5c0b2b167c2b6.png)

(2)补图:
戴眼镜, 化妆,男性,胡须,微笑,年轻
小孩
![avatar](http://www.bbvdd.com/d/20181210121418bco.png)

卡通
![avatar](http://www.bbvdd.com/d/2018121012155476w.png)

亚洲人
![avatar](http://www.bbvdd.com/d/20181210123807hkm.png)

女孩
![avatar](http://www.bbvdd.com/d/201812101240247gf.png)

**Comment by ilydouble** [comment]
老人，小孩，卡通脸行吗？

**Comment by liuwenjie1995** [comment]
已补图, 找不到合适的老人脸,找了一些其他的代替
